### ISSUE TITLE
cosmetics and emotes dont work anymore because of new update maybe

### ISSUE THREAD

**Issue by simplictyy** [Nilsen84/lunar-client-qt#24]
forgot to show in the video that some java agents like no pinned servers arent working anymore (havent tested lunar enable)
staff enable is working though

video:
https://streamable.com/a3ludd

**Comment by Sarreos** [comment]
Yep, it broke because lunar of a lunar update.

**Comment by Yahiachannel42** [comment]
Will it be fixed soon?

**Comment by QTtea** [comment]
hope it gets fixed soon

**Comment by k6d** [comment]
it should be fixed in a day or 2

**Comment by simplictyy** [comment]
cosmetics (cloaks,bandanas,wings) still not working after update

![image](https://user-images.githubusercontent.com/71561421/152343149-64a155a4-707f-4933-b7ff-ec90ad5448ad.png)

emotes and the java agents work though (NoPinnedServers, StaffEnable, and LunarEnable but i didnt get to record it)
https://streamable.com/2b79uq

**Comment by Nilsen84** [comment]
Update lunar and lcqt.
